# Generated by Django 4.1.1 on 2023-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intro_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img'),
        ),
    ]
