# Generated by Django 4.2 on 2023-04-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_purchase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='OrderItem',
        ),
    ]
