# Generated by Django 4.2 on 2023-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_purchase_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
