# Generated by Django 4.2 on 2023-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
