# Generated by Django 4.2 on 2023-05-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_total_order_transcation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_paid',
            field=models.BooleanField(default=False),
        ),
    ]
