# Generated by Django 4.2 on 2023-05-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_online_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
    ]
