# Generated by Django 4.2 on 2023-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_product_avg_rating_product_total_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_ratings',
            new_name='num_of_ratings',
        ),
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
