# Generated by Django 4.2 on 2023-05-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_total_ratings_product_num_of_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_rating',
            new_name='total_ratings',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='num_of_ratings',
            new_name='total_reviews',
        ),
    ]
