# Generated by Django 4.2 on 2023-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_total_rating_product_total_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
